version: '3.8.'
services:
  mysql-db:
    image: mysql:8.0.29
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=backstagedb
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - dbstore:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  backstage-tools:
    image: ghcr.io/bitshifted/backstage-tools:1.0.2
    restart: always
    ports:
      - '3022:22'
    volumes:
      - /tmp:/tmp
  launchcode:
    image: launchcode-dev:latest
    restart: always
    ports:
      - '2022:22'
    volumes:
      - /tmp:/tmp
volumes:
  dbstore:
    driver: local
